// --------------------------------------------------------------------------------------------------------------------
// <summary>
//   Incorporated into the Alpha framework from the Plethora.NET open-source library.
//   http://plethora.codeplex.com/
// </summary>
// <auto-generated> Disable Stylecop - Part of Plethora Context </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using Plethora.Context;

namespace Alpha.ApplicationFramework.Context
{
    using System.Collections.Generic;

    /// <summary>
    /// Interface which allows additional context to be derived from a given context.
    /// </summary>
    /// <remarks>
    /// An instance of <see cref="IContextAugmentor"/> registered with a <see cref="ContextManager"/>
    /// allow the manager to derive additional context from a given context.
    /// </remarks>
    public interface IContextAugmentor
    {
        /// <summary>
        /// The name of the base context.
        /// </summary>
        string ContextName { get; }

        /// <summary>
        /// The augmentation function which takes the base context and returns the derived contexts.
        /// </summary>
        /// <param name="context">
        /// The <see cref="ContextInfo"/> to be augmented. When called this context will have
        /// the name as specified by <see cref="ContextName"/>
        /// </param>
        /// <returns>
        ///  Additional context derived from the input context.
        ///  <remarks>
        ///   May be null if no additional context is available.
        ///  </remarks>
        /// </returns>
        IEnumerable<ContextInfo> Augment(ContextInfo context);
    }
}
