//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4216
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plethora.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plethora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target of invocation has already been disposed..
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item already exists in the collection..
        /// </summary>
        internal static string ArgAddingDuplicate {
            get {
                return ResourceManager.GetString("ArgAddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the collection or &apos;{1}&apos; is greater than the number of elements from &apos;{0}&apos; to the end of the source collection..
        /// </summary>
        internal static string ArgInvaliadOffsetLength {
            get {
                return ResourceManager.GetString("ArgInvaliadOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was invalid..
        /// </summary>
        internal static string ArgInvalid {
            get {
                return ResourceManager.GetString("ArgInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be between {1} and {2}..
        /// </summary>
        internal static string ArgMustBeBetween {
            get {
                return ResourceManager.GetString("ArgMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than {1}..
        /// </summary>
        internal static string ArgMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ArgMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than or equal to {1}..
        /// </summary>
        internal static string ArgMustBeGreaterThanEqualTo {
            get {
                return ResourceManager.GetString("ArgMustBeGreaterThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be less than {1}..
        /// </summary>
        internal static string ArgMustBeLessThan {
            get {
                return ResourceManager.GetString("ArgMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be less than or equal to {1}..
        /// </summary>
        internal static string ArgMustBeLessThanEqualTo {
            get {
                return ResourceManager.GetString("ArgMustBeLessThanEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be of type {1}..
        /// </summary>
        internal static string ArgMustBeOfType {
            get {
                return ResourceManager.GetString("ArgMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be one of {1}..
        /// </summary>
        internal static string ArgMustBeOneOf {
            get {
                return ResourceManager.GetString("ArgMustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{1}&apos; of the parameter &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ArgPropertyInvalid {
            get {
                return ResourceManager.GetString("ArgPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an empty string..
        /// </summary>
        internal static string ArgStringEmpty {
            get {
                return ResourceManager.GetString("ArgStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than or equal to &apos;{1}&apos;, or equal to &apos;{2}&apos;.
        /// </summary>
        internal static string ArgTimeout {
            get {
                return ResourceManager.GetString("ArgTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; is not valid for the enum &apos;{0}&apos;..
        /// </summary>
        internal static string BadEnum {
            get {
                return ResourceManager.GetString("BadEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is readonly..
        /// </summary>
        internal static string CollectionReadonly {
            get {
                return ResourceManager.GetString("CollectionReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic argument must implement IComparable or IComparable&lt;T&gt;; or be an instance of Nullable&lt;T&gt; where T is IComparable or IComparable&lt;T&gt;.
        /// </summary>
        internal static string GenericArgMustBeIComparable {
            get {
                return ResourceManager.GetString("GenericArgMustBeIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of generic arguments provided does not match those of the calling method..
        /// </summary>
        internal static string GenericArgumentsMismatch {
            get {
                return ResourceManager.GetString("GenericArgumentsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified cast is not valid..
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is not in a valid state to execute the operation..
        /// </summary>
        internal static string InvalidState {
            get {
                return ResourceManager.GetString("InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method was not found in the reflected type..
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter type is a generic argument, but could not be found in the list provided..
        /// </summary>
        internal static string ParameterTypeNotInGenericList {
            get {
                return ResourceManager.GetString("ParameterTypeNotInGenericList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MirrorClass was created for a static-only context..
        /// </summary>
        internal static string StaticOnlyMirror {
            get {
                return ResourceManager.GetString("StaticOnlyMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; not found in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string TypeNotFoundInAssembly {
            get {
                return ResourceManager.GetString("TypeNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zero.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
